=== giellalt/dict-nob-fin/scripts/dict_nobfin.dtd
<!ELEMENT e ( lg, mg+ ) >
<!ATTLIST e reverse NMTOKEN #IMPLIED >
<!ATTLIST e src CDATA #IMPLIED >

<!ELEMENT l ( #PCDATA ) >
<!ATTLIST l comment CDATA #IMPLIED >
<!ATTLIST l nr ( Pl ) #IMPLIED >
<!ATTLIST l pos ( A | Abbr | Adv | CC | CS | Clt | Interj |
                  N | Num | Pcle | Po | Pr | Pron | Qu | V | Phrase ) #REQUIRED >
<!ATTLIST l src NMTOKEN #IMPLIED >
<!ATTLIST l val ( IV | TV ) #IMPLIED >
<!ATTLIST l type (Prop) #IMPLIED >

<!ELEMENT lics (lic, ref*, sourcenote*) >
<!ATTLIST lics xml:space (default|preserve) 'preserve'>
<!ELEMENT lic (#PCDATA|a)*>
<!ATTLIST lic xml:lang ( en | nno ) #IMPLIED >
<!ELEMENT ref (#PCDATA|a|i)*>
<!ELEMENT sourcenote (#PCDATA|a|i)*>
<!ELEMENT a (#PCDATA)>
<!ELEMENT i (#PCDATA)>

<!ELEMENT lg ( l ) >

<!ELEMENT mg ( tg ) >

<!ELEMENT r (lics?, e+, xhtml:script?) >
<!ATTLIST r xml:lang (nob) #IMPLIED>
<!ATTLIST r id (nobfin) #IMPLIED>

<!ELEMENT stem ( #PCDATA ) >

<!ELEMENT t ( #PCDATA ) >
<!ATTLIST t comment CDATA #IMPLIED >
<!ATTLIST t gen ( f | m | n ) #IMPLIED >
<!ATTLIST t nr ( Pl ) #IMPLIED >
<!ATTLIST t pos ( A | Adv | CC | CS | Cp | Det | Interj |
                  N | Num | Po | Pr | Pron | V | Phrase ) #REQUIRED >
<!ATTLIST t t_type NMTOKEN #IMPLIED >
<!ATTLIST t type ( Prop ) #IMPLIED >

<!ELEMENT tg ( re? | syng | t | xg )* >
<!ATTLIST tg comment CDATA #IMPLIED >
<!ATTLIST tg xml:lang ( fin ) #IMPLIED >

<!ELEMENT re (#PCDATA) > <!-- Domain restriction: bot, phys, ... -->
<!ATTLIST re
    xml:lang ( nob | fin | sme | sma | smn | swe | eng | deu | lat) #IMPLIED
>
<!ATTLIST re x ( fad ) #IMPLIED >
<!ATTLIST re comment CDATA #IMPLIED >

<!ELEMENT x ( #PCDATA ) >

<!ELEMENT xg ( x, xt ) >

<!ELEMENT xt ( #PCDATA ) >

=== giellalt/dict-nob-fin/src/Prop_nobfin.xml
<?xml version='1.0' encoding='UTF-8'?>
<?xml-stylesheet media="screen"              title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary_XXE.css"     type="text/css"?>
<?xml-stylesheet media="screen"              title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_XXE_alt.css" type="text/css" alternate="yes" ?>
<?xml-stylesheet media="print,tv,projection" title="Dictionary view"   href="../../giella-core/dicts/scripts/gt_dictionary.css"         type="text/css"?>
<?xml-stylesheet media="print,tv,projection" title="Hierarchical view" href="../../giella-core/dicts/scripts/gt_dictionary_alt.css"     type="text/css" alternate="yes" ?>
<!DOCTYPE r PUBLIC "-//DivvunGiellatekno//DTD Dictionaries//Multilingual"
"../scripts/dict_nobfin.dtd">
<r id="nobfin" xml:lang="nob">
  <lics>
    <lic xml:lang="en">
This code is made available under a Creative Commons Attribution license
<a>http://creativecommons.org/licenses/by/3.0/no/deed.en</a>.

You are free to copy, distribute and adapt the work, as long as you always give
proper attribution using the attribution text below.

For the full license text, see the link above.</lic>

    <ref>Work by Trond Trosterud and Kirsti Kuosa at UiT. Source code
          available at <a>https://victorio.uit.no/langtech/trunk/</a>.</ref>

    <sourcenote>
     THIS TEXT IS THE ORIGINAL SOURCE CODE. This is NOT a fully styled and
     published dictionary. As such it can and
     will contain unfinished entries, unpublished entries, entries with
     objectionable translations, etc. If you find any errors or want to add more
     words, download the file, edit it, and send it back to
     <a>mailto:divvun@samediggi.no</a> and <a>mailto:giellatekno@hum.uit.no</a>.
     Please also note that the entries are not necessarily sorted,
     or could be wrongly sorted.
     </sourcenote>
  </lics>

   <e>
      <lg>
         <l pos="N" type="Prop">Afrika</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Afrikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Albania</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Albania</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Amerika</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Amerikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Argentina</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Argentiina</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Armenia</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Armenia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Asia</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Aasia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Aten</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Ateena</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Atlanterhavet</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Atlantti</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Baltikum</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Baltia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Belgia</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Belgia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Berghäll</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Kallio</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Berlin</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Berliini</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Bibelen</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Raamattu</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Bjørneborg</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Pori</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Borgå</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Porvoo</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Bulgaria</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Bulgaria</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Bysants</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Bysantti</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">California</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Kalifornia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Canada</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Kanada</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Cuba</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Kuuba</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Danmark</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Tanska</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Dickursby</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Tikkurila</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Donald Duck</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Aku Ankka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Egypt</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Egypti</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Enare</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Inari</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">England</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Englanti</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Esbo</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Espoo</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Estland</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Viro</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Eurasia</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Euraasia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Europa</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Eurooppa</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Finland</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Suomi</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Frankrike</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Ranska</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Grønland</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Grönlanti</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Gud</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Jumala</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Gustav</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Kustaa</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Handelskompaniet</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Kauppakomppania</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Hellas</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Kreikka</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Helsingfors</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Helsinki</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Holland</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Hollanti</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">India</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Intia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
         <l pos="N" type="Prop">Indonesia</l>
      </lg>
      <mg>
         <tg xml:lang="fin">
            <t pos="N" type="Prop">Indonesia</t>
         </tg>
      </mg>
   </e>
   <e>
      <lg>
